### ISSUE TITLE
Disabling RSpec Cops within Source Code doesn't work with rubocop 0.41.1

### ISSUE THREAD

**Issue by baschtl** [nevir/rubocop-rspec#112] opened 2016-06-27 12:19 UTC
Hi,

we use some [inline disabling of rubocop](http://rubocop.readthedocs.io/en/latest/configuration/#disabling-cops-within-source-code) in our code (i.e., `# rubocop:disable RSpec/AnyInstance`). After we updated from rubocop 0.40.0 to rubocop 0.41.1 this does not work anymore for RSpec cops provided by this gem.

We use rubocop-rspec 1.5.0.

Does somebody know what changed here?

**Comment by tjwp** [comment] 2016-06-27 13:12
I think the problem is the change made here to allow arbitrary comments after inline disabling:

https://github.com/bbatsov/rubocop/pull/3201/files#diff-aaa82a90d90f9a0d9c9c4048a224fde2R10

The new regexp `([A-Z][a-z]+/)?(?:[A-Z][a-z]+)+` is too restrictive and does not allow `RSpec`.

**Comment by tjwp** [comment] 2016-06-27 13:37
Opened a PR for rubocop: https://github.com/bbatsov/rubocop/pull/3250

**Comment by backus** [comment] 2016-08-03 08:34
Since it looks like @tjwp's contribution to rubocop was merged I'm going to close this. @baschtl please reopen if you disagree

**Closed by backus** 2016-08-03 08:34 UTC
