### ISSUE TITLE
Spec path should end with `. . . *_spec.rb` incorrectly being thrown.

### ISSUE THREAD

**Issue by kWhittington** [nevir/rubocop-rspec#37] opened 2015-04-29 17:30 UTC
Hi,

After looking at some of the source file that throws the spec pathing offense, I think it might be getting thrown by accident for describe blocks for nested classes/modules.

Here's the example code that's causing the error:
```ruby
require 'spec_helper'

tags = { . . . meta_data . . .}

RSpec.describe Module::PluralizedModelController, tags do
end
```

Rubocop reports `Spec path should end with 'module/pluralized_model_controller*_spec.rb'` but the file follows that format. `pluralized_model_controller_spec.rb` is within a folder named `module`.

There isn't anything else in the file and the error is repeatable with the example I've given above. Could there be a Regexp issue with https://github.com/nevir/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/file_path.rb?

Thanks!

**Comment by adarsh** [comment] 2015-08-21 19:17
+1

**Comment by ehannes** [comment] 2015-10-19 16:04
I had the same problem, but I had misspelled the directory name. When I corrected the spelling the offense was gone.

**Comment by seanlerner** [comment] 2016-03-09 23:25
I had this issue with `companies_spec.rb`
The cop was happy if I named the file `companys_spec.rb`
but instead I disabled this cop with ` # rubocop:disable RSpec/FilePath`

**Comment by andyw8** [comment] 2016-05-08 21:04
@kWhittington @adarsh: I'm having trouble reproducing this problem. Could you confirm if it's still happening in the latest release?

@seanlerner: that sounds like it might be a separate issue. Could you give some more details about what your spec file's contents?

**Comment by kWhittington** [comment] 2016-05-08 21:24
I just tried it again in the app it was happening in. I'm not getting the error in our controller specs anymore. We've updated `rubocop` and `rubocop-rspec` since I first reported this:
```
rubocop (0.39.0)
  parser (>= 2.3.0.7, < 3.0)
  powerpack (~> 0.1)
  rainbow (>= 1.99.1, < 3.0)
  ruby-progressbar (~> 1.7)
  unicode-display_width (~> 1.0, >= 1.0.1)
rubocop-rspec (1.4.1)
  rubocop (= 0.39.0)
```

Thanks for asking.

**Comment by adarsh** [comment] 2016-05-08 22:01
Sorry for not closing the loop here - I realized the spec file was
mis-named and that was the root problem. I'm okay closing this issue, at
least from my end.



-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal

**Comment by seanlerner** [comment] 2016-05-10 13:58
@andyw8 - I'm not able to reproduce the issue any longer. (I've moved away from 'Company' as a model name). thx for following up.

**Comment by vladlena** [comment] 2016-07-13 16:34
+1 directory name misspelling

**Comment by andyw8** [comment] 2016-07-14 08:51
@vladlena please provide some information about how to reproduce your problem.

**Comment by backus** [comment] 2016-08-03 08:38
Looks like everyone reporting issues here wound up figuring out their problem. Closing this. Let me know if anyone still has problems

**Closed by backus** 2016-08-03 08:38 UTC

**Comment by nowakov** [comment] 2017-06-03 09:51
@backus Hey. I have similar issue with acronym controller name.
My controller is named: `POIsController` and `POI` is added to rails' inflections, but rubocop shouts:
```sh
spec/controllers/pois_controller_spec.rb:4:1: C: RSpec/FilePath: Spec path should end with po_is_controller*_spec.rb.
```

**Comment by andyw8** [comment] 2017-06-03 15:05
@nowakov rubocop-rspec does not read from the Rails reflections, but you can define a CustomTransform:

```
RSpec/FilePath:
  CustomTransform:
    POIsController: pois_controller
```

https://github.com/backus/rubocop-rspec/blob/master/lib/rubocop/cop/rspec/file_path.rb

**Comment by nowakov** [comment] 2017-06-05 14:06
@andyw8 Fair enough. Thanks! 🎉
